### ISSUE TITLE
PCC should have a __str__ that returns the actual class instead of Set

### ISSUE THREAD

**Issue by arthur00** [Mondego/spacetime#12]
When we print a pcc_set type we get <class Set> instead of the actual object. PCC set types should instead print the name of the original class, or some derivation that includes it.

**Comment by arthur00** [comment]
@lordnahor what is your opinion on this?

**Comment by rohan-achar** [comment]
yep. latest PCC code has this change, when I push it to spacetime, it should be there.

**Comment by arthur00** [comment]
Ok, closing "as solved by latest pcc"
