### ISSUE TITLE
PCC set properties are getting mixed up on push/pull

### ISSUE THREAD

**Issue by arthur00** [Mondego/spacetime#16]
On my NodeSimulation code, I create Waypoints, Nodes, and Routes. For every Node, a waypoint is attached to it (no exceptions).

On the NodeTestSimulation, I create RouteRequest, and subscribe to Route and Nodes. At some point, when parsing the nodes of the simulation, I run into a Node that has no Waypoint set (which should not happen), and it has the name of a RouteRequest. Apparently the field "Name" is getting mixed up in the spacetime library somewhere. 

The simulation code is available on the branch bug_nodesim.

**Comment by rohan-achar** [comment]
Isn't this done? Can't we close it?
