### ISSUE TITLE
Fetch all relevant objects in the beginning

### ISSUE THREAD

**Issue by crista** [Mondego/spacetime#25]
When an app starts, right now it only gets objects that are placed in the store [by other apps] after the this app started. This is a problem, for example, for visualizers.

We could do it in the pull of the update loop, but that's a bad idea, because this initial pulling of data can potentially be very large. It needs to be done at initialization.

**Comment by arthur00** [comment]
This was on my to-do list for a while, thanks for completing it!

**Comment by arthur00** [comment]
Seems to be working so far! We can reopen if something bad happens..
