### ISSUE TITLE
Make only 1 server requests for updates/pushes

### ISSUE THREAD

**Issue by arthur00** [Mondego/spacetime#48]
We are doing 2 requests at every pull: one for tracked, one for updates. This means two roundtrips to the server. We should bundle them in one call. @lordnahor, opinion?
Update: Push is also sending one request per type

**Comment by crista** [comment]
There should be only one request per pull and one request per push.

**Comment by arthur00** [comment]
I just noticed that our push is also doing 1 request per type. I am modifying it to be just one call as well
