### ISSUE TITLE
Implement get_new, get_mod, get_del for subsets

### ISSUE THREAD

**Issue by arthur00** [Mondego/spacetime#61]
get_new, get_mod, and get_del are not working for subsets

**Comment by crista** [comment]
This is biting me. Please fix it, not just for subsets, but for all PCCs

**Comment by crista** [comment]
Root of the problem, this comment in the code "pccs are always recalculated from scratch. Easier"

**Comment by rohan-achar** [comment]
This is complete with the latest dataframe changes. merged with checkin d39539ea23b1459f9f2daf05190eae11eccb9132
