### ISSUE TITLE
Send only ids for subsets

### ISSUE THREAD

**Issue by arthur00** [Mondego/spacetime#62]
Since subsets never have more information than the original set object, a subset can essentially be represented as a list of ids, as long as the client also subscribes to the parent set as well.

A suggestion was for the server to send a dictionary with primary keys as ids and set an empty dictionary as a value when the server wishes the client to use its local copy of that object.

**Comment by rohan-achar** [comment]
This is done in part in checkin d39539ea23b1459f9f2daf05190eae11eccb9132.
Only modifications to dimensions, and the corresponding ids are sent during update.
